basic/factorial.py

solving: bugs

---

basic/fibonacci-sequence.py

add: fibonacci-sequence.py

---

basic/count-vowels-consonants.py

added count-vowels-consonants.py

add: count-vowels-consonants.py

---

basic/reverse-linked-list.py

add: reverse-linked-list.py

---

basic/merge-two-sorted-list.py

add: merge-two-sorted-list.py

---

basic/find-missing-number-in-list.py

add:  find-missing-number-in-list.py

add:  find-missing-number-in-list.py

---

basic/binary-search.py

add: binary-search.py

---

basic/valid-parentheses.py

add: valid-parentheses.py

---

basic/max-subarray.py

add: max-subarray.py

---

basic/merge-intervals.py

add: merge-intervals.py

---

basic/kth-largest-element.py

add: kth-largest-element.py

---

sorting/bubble-sort.py

add: bubble-sort.py

---

sorting/selection-sort.py

add: selection-sort.py

---

sorting/insertion-sort.py

add: insertion-sort.py

---

sorting/merge-sort.py

add: merge-sort.py

---

sorting/quick-sort.py

add: quick-sort.py

---

sorting/counting-sort.py

add: counting-sort.py

---

sorting/radix-sort.py

add: radix-sort.py

---

interview-questions/binary-tree-inorder-traversal.py

add: binary-tree-inorder-traversal.py

add: binary-tree-inorder-traversal.py

---

interview-questions/lowest-common-ancestor-of-binary-tree.py

add: lowest-common-ancestor-of-binary-tree.py

add: lowest-common-ancestor-of-binary-tree.py

---

interview-questions/number-of-islands.py

add: number-of-islands.py

---

README.md

update: updated readme file
